FROM maven:3.9.6-eclipse-temurin-21

WORKDIR /app

RUN apt-get update && apt-get install -y netcat

# Copy your entire project (pom.xml, src/...) into the container
COPY . .

# Simply run Maven tests when the container starts
CMD ["mvn", "clean", "test"]

