services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - apiario_net

  auth-service:
    build:
      context: ./microservice-auth
    container_name: auth-service
    ports:
      - "${AUTH_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - apiario_net

  apiari-service:
    build:
      context: ./microservice-apiari
    container_name: apiari-service
    ports:
      - "${APIARI_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - apiario_net

  backoffice-service:
    build:
      context: ./microservice-backoffice
    container_name: backoffice-service
    ports:
      - "${BACKOFFICE_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - apiario_net

  frontend:
    build:
      context: ./la-casa-del-miele
      dockerfile: Dockerfile
    container_name: frontend-angular
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - auth-service
      - apiari-service
      - backoffice-service
    networks:
      - apiario_net

volumes:
  mysql_data:



networks:
  apiario_net:
    driver: bridge
