services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db-test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mieli_db_test
    ports:
      - "3307:3306" # Porta diversa per evitare conflitto
    volumes:
      - mysql_data_test:/var/lib/mysql
    networks:
      - apiario_test_net

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-runner
    depends_on:
      - mysql-db
    networks:
      - apiario_test_net
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db-test:3306/mieli_db_test"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: test
    entrypoint: ["/bin/bash", "-c", "./wait-for-it.sh mysql-db-test:3306 -t 60 --strict -- mvn clean test"]

volumes:
  mysql_data_test:

networks:
  apiario_test_net:
    driver: bridge
