services:
  # ---------- DATABASES ----------
  db-apiari:
    image: mysql
    container_name: db-apiari
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apiari_db
    ports: ["3307:3306"]
    networks: [apiario-network]
    volumes: [db-data-apiari:/var/lib/mysql]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-auth:
    image: mysql
    container_name: db-auth
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports: ["3309:3306"]
    networks: [apiario-network]
    volumes: [db-data-auth:/var/lib/mysql]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  # ---------- MICROSERVICES ----------
  microservice-apiari:
    build: ./microservice-apiari
    image: la-casa-del-miele/microservice-apiari
    ports: ["8081:8080"]       # 8080 inside the container
    depends_on:
      db-apiari:
        condition: service_healthy
    networks: [apiario-network]

  microservice-auth:
    build: ./microservice-auth
    image: la-casa-del-miele/microservice-auth
    ports: ["8082:8080"]
    depends_on:
      db-auth:
        condition: service_healthy
    networks: [apiario-network]
volumes:
  db-data-auth:
  db-data-apiari:

networks:
  apiario-network:
    driver: bridge

